name: mackup
base: core24
version: git
summary: Keep your application settings in sync
description: |
  Back ups your application settings in a safe directory (e.g. Dropbox).
  Syncs your application settings among all your workstations.
  Restores your configuration on any fresh install in one command line.

grade: stable
confinement: strict

apps:
  mackup:
    command: bin/mackup
    plugs:
      - home

parts:
  mackup:
    plugin: python
    source: .
