name: Lint Python
on:
  - pull_request
  - push

jobs:

  black:
    runs-on: ubuntu-latest
    container: python
    steps:
      - run: pip install black
      - uses: actions/checkout@v4
      - run: black --check --target-version py310 .
