name: Mackup
on: [push, pull_request]

jobs:

  mdl:
    runs-on: ubuntu-latest
    container: rsrchboy/mdl
    steps:
      - uses: actions/checkout@v2
      - run: mdl .

  black:
    runs-on: ubuntu-latest
    container: python
    steps:
      - run: pip install black
      - uses: actions/checkout@v2
      - run: black --check --target-version py27 .

  nose-2_7:
    runs-on: ubuntu-latest
    container: python:2.7
    steps:
      - run: pip install docopt six nose
      - uses: actions/checkout@v2
      - run: nosetests --with-coverage --cover-tests --cover-inclusive --cover-branches --cover-package=mackup

  nose-3_6:
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
      - run: pip install pipenv
      - uses: actions/checkout@v2
      - run: pipenv install -d
      - run: make test

  nose-3_7:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - run: pip install pipenv
      - uses: actions/checkout@v2
      - run: pipenv install -d
      - run: make test

  nose-3_8:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - run: pip install pipenv
      - uses: actions/checkout@v2
      - run: pipenv install -d
      - run: make test

  install-2_7:
    runs-on: ubuntu-latest
    container: python:2.7
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: mackup --help

  install-3_6:
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: mackup --help

  install-3_7:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: mackup --help

  install-3_8:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py install
      - run: mackup --help
